USERNAME = "anguinau"
SERVER_NAME = "#{USERNAME}S"

INFRA_DIR = "k8s"
SCRIPTS_DIR = "script"

SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-13"

  config.vm.synced_folder "./volume", "/vagrant"
  config.vm.synced_folder "./#{INFRA_DIR}", "/#{INFRA_DIR}"

  config.vm.define SERVER_NAME do |server|

    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vbox|

      vbox.customize ["modifyvm", :id, "--name", SERVER_NAME]
      vbox.memory = 4096
      vbox.cpus = 2
    end
    server.vm.provision "shell",
      path: "#{SCRIPTS_DIR}/setup.sh",
      args: [SERVER_IP]

    server.vm.provision "shell",
      path: "#{SCRIPTS_DIR}/deploy.sh",
      args: [SERVER_IP]
  end
end
